apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-acs-operator
  namespace: openshift-gitops
spec:
  generators:
  # Only select external clusters, excludes local cluster
  - clusters:
      selector:
        matchLabels:
          #argocd.argoproj.io/secret-type: cluster
          acs: "true"
  template:
    metadata:
      name: "{{nameNormalized}}-openshift-acs-operator"
    spec:
      project: default
      source:
        repoURL: https://git.detran.ba.gov.br/PlataformaBaixa/Gitops-infra
        targetRevision: main
        path: applicationsets/openshift-acs-operator/manifests/
      destination:
        server: "{{server}}"
        namespace: rhacs-operator
      syncPolicy:
        syncOptions:
        - CreateNamespace=true      
        automated:
          selfHeal: true
          prune: true