---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base
  - oauth-ldap-patch.yaml
  - ldap-secret.yaml  
patches:
  - path: oauth-ldap-patch.yaml
    target:
      group: config.openshift.io
      kind: OAuth
      name: cluster
      version: v1