---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-loki-secret-cr-openshift-logging
  labels:
    app: create-loki-secret-cr-openshift-logging
rules:
- apiGroups: [""] 
  resources: ["nodes","namespaces"]
  verbs: ["get","list"]
- apiGroups: [""] 
  resources: ["pods","configmap", "secret","pods/log","namespaces"]
  verbs: ["get", "list", "create", "delete", "watch"]