kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-loki-secret-crb-openshift-logging
  labels:
    app: create-loki-secret-crb-openshift-logging
subjects:
  - kind: ServiceAccount
    name: create-loki-secret-sa
    namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-loki-secret-cr-openshift-logging