---
apiVersion: v1
kind: Namespace
metadata:
  name: ocp-etcd-backup
  labels:
    app: openshift-backup
  annotations:
    openshift.io/description: "Openshift Backup Automation Tool"
    openshift.io/display-name: "Backup ETCD Automation"

