---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: ocp-etcd-backup
  labels:
    app: openshift-backup
  annotations:
    openshift.io/node-selector: ''
    pod-security.kubernetes.io/enforce: privileged
    openshift.io/description: "Openshift Backup Automation Tool"
    openshift.io/display-name: "Backup ETCD Automation"
spec:
  finalizers:
    - kubernetes
