---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pvc.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/storage
        value:
          pvc:
            claim: 'image-registry-storage'
      - op: replace
        path: /spec/rolloutStrategy
        value: 'Recreate'
    target:
      kind: Config
      name: cluster

