apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nmstate
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - appName: operator
        path: applicationsets/openshift-nmstate-all-in-one/operator/
      - appName: instance
        path: applicationsets/openshift-nmstate-all-in-one/instance/        
      - appName: dns-detran
        path: applicationsets/openshift-nmstate-all-in-one/dns/ 
  template:
    metadata:
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
      name: "nmstate-{{appName}}-masrl"
    spec:
      project: default
      source:
        repoURL: https://github.com/marcosraposo/demo-gitops.git 
        targetRevision: main
        path: "{{path}}"
      destination:
        name: masrl
        namespace: openshift-nmstate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ApplyOutOfSyncOnly=true 