apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-nmstate-dns-detran
spec:
  destination:
    namespace: openshift-nmstate
    name: malima
  source:
    repoURL: https://github.com/marcosraposo/demo-gitops.git    
    path: applicationsets/openshift-nmstate-all-in-one/operator/
    targetRevision: HEAD  
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ApplyOutOfSyncOnly=true

