apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-nmstate-operator
  namespace: openshift-gitops
spec:
  generators:
  # Only select external clusters, excludes local cluster
  - clusters:
      selector:
        matchLabels:
          #argocd.argoproj.io/secret-type: cluster
          nmstate: "true"
  template:
    metadata:
      name: "{{nameNormalized}}-openshift-nmstate-operator"
    spec:
      project: default
      source:
        repoURL: https://git.detran.ba.gov.br/PlataformaBaixa/Gitops-infra
        targetRevision: main
        path: applicationsets/openshift-nmstate/manifests/
      destination:
        server: "{{server}}"
        namespace: openshift-nmstate
      syncPolicy:
        syncOptions:
        - CreateNamespace=true      
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        #  - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
#          - Delete=confirm
          - ApplyOutOfSyncOnly=true
        #  - PruneLast=true
        #  - Replace=true          