kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-registry-secret-crb-openshift-registy
  labels:
    app: create-registy-secret-crb-openshift-registy
subjects:
  - kind: ServiceAccount
    name: create-registy-secret-sa
    namespace: openshift-registy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-registy-secret-cr-openshift-registy