---
kind: Job
apiVersion: batch/v1
metadata:
  name: create-registy-bucket-secret
  namespace: openshift-logging
  labels:
    app: create-registy-bucket-secret
spec:
  template:
    metadata:
      name: create-registy-secret
    spec:
      containers:
        - name: create-registy-secret
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash

              # Sleeping before starting with the work, to be sure the bucket has been created.
              SLEEPER_TMP=0

              printf "Waiting 20 seconds before I start with the generation of the configuration\n"
             
              while [[ $SLEEPER_TMP -le "20" ]]; do
                echo -n "."
                sleep 1
                SLEEPER_TMP=$(($SLEEPER_TMP+1))
              done

              printf "\nTrying to create the required registy secret file\n"

              bucket_user=`cat /tmp/bucket-secret/AWS_ACCESS_KEY_ID`

              bucket_secret=`cat /tmp/bucket-secret/AWS_SECRET_ACCESS_KEY`

              bucket_name=`cat /tmp/registy-bucket/BUCKET_NAME`

              bucket_host=`cat /tmp/registy-bucket/BUCKET_HOST`

              bucket_region=`cat /tmp/registy-bucket/BUCKET_REGION`

              oc -n openshift-logging create secret generic logging-loki-s3 --from-literal access_key_id=${bucket_user} \
              --from-literal access_key_secret=${bucket_secret} \
              --from-literal bucketnames=${bucket_name} \
              --from-literal endpoint=https://${bucket_host} \
              --from-literal region=${bucket_region} \

              printf "\nSecret logging-loki-s3 has been created\n"
          volumeMounts:
            - name: bucket-secret
              mountPath: "/tmp/bucket-secret"
              readOnly: true
            - name: loki-bucket
              mountPath: /tmp/loki-bucket
      volumes:
        - name: bucket-secret
          secret:
            secretName: loki-bucket-odf
        - name: loki-bucket
          configMap:
            name: loki-bucket-odf
      restartPolicy: Never
      serviceAccountName: create-loki-secret-sa