---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-registy-secret-cr-openshift-registy
  labels:
    app: create-registy-secret-cr-openshift-registy
rules:
- apiGroups: [""] 
  resources: ["nodes","namespaces"]
  verbs: ["get","list"]
- apiGroups: [""] 
  resources: ["pods","configmap","secrets","pods/log","namespaces"]
  verbs: ["get", "list", "create", "delete", "watch"]