---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
  - ../../../operator/overlays/stable
  - ../../../instance/overlays/vsphere
  - ../../../config-helpers/node-labeler/overlays/default