apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-compliance

resources:
  - namespace.yml
  - operatorgroup.yml
  - subscription.yml
  - scanSettingBinding-cis.yml
  - scanSetting-cis.yml  
  - TailoredProfile-newprofile.yml

