apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "ocs-volumeset"
  namespace: "openshift-local-storage"
spec:
  tolerations:
  - effect: NoSchedule
    key: node.ocs.openshift.io/storage
    value: "true"
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: cluster.ocs.openshift.io/openshift-storage
        operator: In
        values:
           - ''
  storageClassDevices:
  - storageClassName: "local-sc"
    volumeMode: Block
    devicePaths:
    - /dev/sdb