apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocp-etcd-backup
  namespace: openshift-gitops
spec:
  generators:
  # Only select external clusters, excludes local cluster
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: "{{nameNormalized}}-backup-etcd"
    spec:
      project: default
      source:
        repoURL: https://github.com/marcosraposo/demo-gitops.git
        targetRevision: main
        path: applicationsets/backup-etcd/manifests
      destination:
        server: "{{server}}"
        namespace: ocp-etcd-backup
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true