apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: worker-dns-detran
  namespace: openshift-nmstate
  annotations:
    argocd.argoproj.io/sync-wave: "4"    
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  desiredState:
    dns-resolver:
      config:
        search:
          - detrandom.tran
        server:
          - 10.21.246.3
          - 10.21.246.10
