apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-nmstate-dns-detran-masrl
spec:
  destination:
    namespace: openshift-nmstate
    name: masrl
  source:
    path: applicationsets/openshift-nmstate/dns-detran/
    repoURL: https://github.com/marcosraposo/demo-gitops.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true