apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-logging

resources:

  - namespace-logging.yaml
  - namespace-operator-loki.yaml
  - observability-operator.yaml
  - observability-uplugin.yaml
  - operator-group-logging.yaml
  - subscription-logging.yaml
  - subscription-loki.yaml